# Generated by Django 3.1.4 on 2021-08-21 15:00

from django.db import migrations, models
import product.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=product.models.photo_upload_path)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('preparation', models.TextField()),
                ('recomends', models.JSONField(default={})),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
