# Generated by Django 3.1.4 on 2021-08-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210821_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recomends',
            field=models.JSONField(default={}),
        ),
    ]
