# Generated by Django 3.1.4 on 2021-08-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210821_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recomends',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
