version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8080:8000
    volumes:
      - .:/usr/src/app/web
    env_file:
      - ./envfiles/.env.dev
    depends_on:
      - db
    
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file: 
      - ./envfiles/.env.dev.db

volumes:
  postgres_data_dev: