version: '3.7'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8080:8000
    volumes:
      - static_volume:/usr/src/app/web/staticfiles
      - media_volume:/usr/src/app/web/mediafiles
    env_file:
      - ./envfiles/.env.prod
    depends_on:
      - db
    networks: 
      - meadx_network

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envfiles/.env.prod.db
    networks: 
      - meadx_network

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/usr/src/app/web/staticfiles
      - media_volume:/usr/src/app/web/mediafiles
    networks:
      - meadx_network
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  meadx_network:
    driver: bridge