# Generated by Django 3.1.4 on 2021-08-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210821_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.JSONField(),
        ),
    ]
